name: Run JMeter Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Download Apache JMeter
        run: |
          curl -L https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz -o jmeter.tgz
          tar -xzf jmeter.tgz
          mv apache-jmeter-5.6.3 jmeter

      # Executa o primeiro teste
      - name: Run JMeter test 01 (non-GUI mode)
        run: |
          ./jmeter/bin/jmeter \
            -n \
            -t tests/testes-api-01.jmx \
            -l results-01.jtl \
            -e -o reports-01

      # Executa o segundo teste
      - name: Run JMeter test 02 (non-GUI mode)
        run: |
          ./jmeter/bin/jmeter \
            -n \
            -t tests/testes-api-02.jmx \
            -l results-02.jtl \
            -e -o reports-02

      - name: Upload JMeter results (JTL + HTML report)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: |
            results-01.jtl
            reports-01/**
            results-02.jtl
            reports-02/**
